import React, { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import "../styles/trainingdetail.css";
import jsPDF from "jspdf";

const TrainingDetail = () => {
    const { name } = useParams();
    const navigate = useNavigate();

    const programs = [
        { title: "🏁 Beginner Full-Body Program", short: "Perfect for newcomers learning the basics.", details: "Light weights, form training, mobility sessions, and gradual strength progression." },
        { title: "🔥 Weight Loss / Fat Burn Program", short: "High-intensity calorie-burning routine.", details: "HIIT, circuits, fat-burn cardio, and metabolic conditioning sessions." },
        { title: "💪 Muscle Gain (Hypertrophy)", short: "Maximize muscle growth and strength.", details: "High-volume workouts, progressive overload, and targeted muscle isolation." },
        { title: "🏋️ Strength Training (Power)", short: "Focused on heavy compound lifting.", details: "5×5 strength training, low reps, heavy weight, and progressive overload." },
        { title: "⚡ Athlete Conditioning Program", short: "Speed, agility, explosiveness.", details: "Plyometrics, sprints, explosive movements, and high-performance conditioning." },
        { title: "🏆 5-Day Bodybuilding Split", short: "Classic physique-building training.", details: "Body-part splits, high volume, and maximum muscle isolation." },
    ];

    const decodedName = decodeURIComponent(name);
    const program = programs.find(p => p.title === decodedName);

    if (!program) {
        return (
            <div className="training-detail-page">
                <div className="training-detail-container">
                    <h1>Program Not Found</h1>
                    <p>The training program you're looking for doesn't exist.</p>
                    <button onClick={() => navigate("/training-programs")}>
                        Back to Programs
                    </button>
                </div>
            </div>
        );
    }

    const handleGetCoach = () => {
        navigate("/coaches");
    };

    const handleDownloadPDF = () => {
        const doc = new jsPDF("p", "mm", "a4");
        const logo = new Image();
        logo.src = require("../assets/logo.png");

        logo.onload = () => {
            doc.addImage(logo, "PNG", 80, 10, 50, 50);
            generatePDFContent(doc);
        };

        logo.onerror = () => {
            generatePDFContent(doc);
        };
    };

    const generatePDFContent = (doc) => {
        let y = 70;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(22);
        doc.text(program.title, 105, y, { align: "center" });
        y += 15;

        doc.setFontSize(14);
        doc.text("Program Summary:", 20, y);
        y += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.text(doc.splitTextToSize(program.short, 170), 20, y);
        y += 20;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Details:", 20, y);
        y += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.text(doc.splitTextToSize(program.details, 170), 20, y);

        doc.setFont("helvetica", "italic");
        doc.setFontSize(10);
        doc.text("Generated by Bi To Tri Gym — Train Hard, Transform Harder.", 105, 290, { align: "center" });

        const safeTitle = program.title.replace(/[^a-z0-9]/gi, "_");
        doc.save(`${safeTitle}_4-week-plan.pdf`);
    };

    return (
        <div className="training-detail-page">
            <div className="training-detail-container">
                <button className="back-button" onClick={() => navigate("/training-programs")}>
                    ← Back to Programs
                </button>

                <div className="program-header">
                    <h1>{program.title}</h1>
                    <p className="program-short">{program.short}</p>
                </div>

                <div className="program-content">
                    <div className="program-section">
                        <h2>Program Overview</h2>
                        <p className="program-details">{program.details}</p>
                    </div>

                    <div className="program-section">
                        <h2>What's Included</h2>
                        <ul className="program-features">
                            <li>4-week structured training plan</li>
                            <li>Detailed workout instructions</li>
                            <li>Progressive overload guidelines</li>
                            <li>Recovery and rest day recommendations</li>
                            <li>Nutrition tips for optimal results</li>
                        </ul>
                    </div>

                    <div className="program-actions">
                        <button className="coach-button" onClick={handleGetCoach}>
                            Get a Coach
                        </button>
                        <button className="pdf-button" onClick={handleDownloadPDF}>
                            Download PDF
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TrainingDetail;

